"""Benchmark the board and emit a markdown table.

Runs a fixed set of measurements against reference silicon, formats the
results as a markdown table, and writes it to docs/THROUGHPUT.md. The
hash of the table is printed so CI can detect drift between runs.

Usage:
    python scripts/bench_report.py             # run benchmarks and write
    python scripts/bench_report.py --check     # verify current file is up to date
"""
from __future__ import annotations

import argparse
import hashlib
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REPORT = REPO / "docs" / "THROUGHPUT.md"


def run_benchmarks() -> dict[str, float]:
    """Drive the board through a fixed workload. Returns measurements dict."""
    sys.path.insert(0, str(REPO))
    from icepi.flash_service import FlashService

    results: dict[str, float] = {}
    with FlashService() as svc:
        svc.assert_service()

        # PING round-trip (UART RTT floor)
        n = 200
        t0 = time.perf_counter()
        for _ in range(n):
            svc.ping()
        results["ping_ms"] = (time.perf_counter() - t0) / n * 1000

        # Flash READ16 (one chunk)
        n = 100
        t0 = time.perf_counter()
        for i in range(n):
            svc.read16(i * 16)
        results["flash_read16_ms"] = (time.perf_counter() - t0) / n * 1000
        results["flash_read_kbps"] = 16.0 / (results["flash_read16_ms"] / 1000) / 1024

        # SDRAM single-word round-trip
        pat = bytes(range(16))
        n = 100
        t0 = time.perf_counter()
        for _ in range(n):
            svc.sdram_write16(0x000000, pat)
            svc.sdram_read16(0x000000)
        results["sdram_rt_ms"] = (time.perf_counter() - t0) / n * 1000

        # Stream throughput at four sizes
        for sz in (1024, 4096, 16384, 32768):
            payload = bytes([(i * 37) & 0xFF for i in range(sz)])
            t0 = time.perf_counter()
            svc.sdram_write_stream(0, payload, timeout=30.0)
            elapsed = time.perf_counter() - t0
            results[f"stream_{sz}_kbps"] = (sz / elapsed) / 1024

        # Amortized install path: tiny synthetic bitstream through the staged path.
        import tempfile
        pattern = bytes([(i * 37 + 0xC5) & 0xFF for i in range(8192)])
        with tempfile.NamedTemporaryFile(suffix=".bit", delete=False) as tf:
            tf.write(pattern)
            tmp = Path(tf.name)
        try:
            svc.erase64(0x300000)
            t0 = time.perf_counter()
            svc.upload_bitstream(tmp, base_address=0x300000, verify=True)
            elapsed = time.perf_counter() - t0
            results["install_8k_staged_s"] = elapsed
            results["install_8k_staged_kbps"] = (8192 / elapsed) / 1024
            svc.erase64(0x300000)
        finally:
            tmp.unlink(missing_ok=True)

        # Final command count so we can see we didn't leak commands
        stats = svc.stats()
        results["final_cmd_count"] = float(stats.command_count)

    return results


def _bucket_ms(value: float) -> str:
    """Bucket milliseconds to 0.5 ms granularity for stable run-to-run output."""
    return f"{round(value * 2) / 2:.1f}"


def _bucket_kbps(value: float) -> str:
    """Bucket KB/s to 0.5 KB/s granularity."""
    return f"{round(value * 2) / 2:.1f}"


def _bucket_seconds(value: float) -> str:
    """Bucket seconds to 0.1 s granularity."""
    return f"{round(value, 1):.1f}"


def render_table(results: dict[str, float]) -> str:
    """Format benchmark results as a markdown table with bucketed values
    so run-to-run variation below noise threshold does not trigger drift."""
    lines = [
        "# Reference Silicon Throughput",
        "",
        "Regenerated by `scripts/bench_report.py` on every reference silicon run.",
        "Do not edit by hand — drift is detected by CI.",
        "",
        "Values are bucketed (0.5 ms / 0.5 KB/s / 0.1 s) so run-to-run noise",
        "does not fail the drift check. A failed check means something moved",
        "more than the bucket width — investigate before committing.",
        "",
        "| Measurement | Value |",
        "|---|---|",
        f"| UART PING round-trip | {_bucket_ms(results['ping_ms'])} ms |",
        f"| Flash READ16 single chunk | {_bucket_ms(results['flash_read16_ms'])} ms ({_bucket_kbps(results['flash_read_kbps'])} KB/s) |",
        f"| SDRAM single-word round-trip (write + read) | {_bucket_ms(results['sdram_rt_ms'])} ms |",
        f"| Stream 1 KB into SDRAM | {_bucket_kbps(results['stream_1024_kbps'])} KB/s |",
        f"| Stream 4 KB into SDRAM | {_bucket_kbps(results['stream_4096_kbps'])} KB/s |",
        f"| Stream 16 KB into SDRAM | {_bucket_kbps(results['stream_16384_kbps'])} KB/s |",
        f"| Stream 32 KB into SDRAM | {_bucket_kbps(results['stream_32768_kbps'])} KB/s |",
        f"| 8 KB install via staged path (unlock + commit + verify) | {_bucket_seconds(results['install_8k_staged_s'])} s ({_bucket_kbps(results['install_8k_staged_kbps'])} KB/s) |",
        "",
        "Generated from reference silicon. For a 200 KB install through the",
        "same staged path, extrapolate: ~25× the 8 KB figure (linear in SDRAM",
        "stream time, constant in on-board commit overhead).",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/THROUGHPUT.md from silicon")
    parser.add_argument("--check", action="store_true", help="verify current file is up to date")
    args = parser.parse_args()

    results = run_benchmarks()
    content = render_table(results)
    REPORT.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        if not REPORT.exists():
            print(f"error: {REPORT} does not exist — run without --check first", file=sys.stderr)
            return 1
        current = REPORT.read_text(encoding="utf-8")
        if current == content:
            print(f"{REPORT}: up to date")
            return 0
        print(f"error: {REPORT} is out of date", file=sys.stderr)
        print(f"  current hash: {hashlib.sha256(current.encode()).hexdigest()[:16]}", file=sys.stderr)
        print(f"  fresh   hash: {hashlib.sha256(content.encode()).hexdigest()[:16]}", file=sys.stderr)
        print("Re-run `python scripts/bench_report.py` on reference silicon.", file=sys.stderr)
        return 1

    REPORT.write_text(content, encoding="utf-8")
    print(f"wrote {REPORT} ({len(content)} bytes)")
    print(f"sha256: {hashlib.sha256(content.encode()).hexdigest()[:16]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
